runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_files: www/index.html
    upload: www/index.html
    expiration: "2s"

  - url: /(.*)
    static_files: www/\1
    upload: www/(.*)
    expiration: "2s"
